// Objective-C API for talking to github.com/xtls/libxray/libv2ray Go package.
//   gobind -lang=objc github.com/xtls/libxray/libv2ray
//
// File is generated by gobind. Do not edit.

#ifndef __Libv2ray_H__
#define __Libv2ray_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * CheckVersionX — устаревший alias для XrayVersion.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayCheckVersionX(void);

/**
 * CleanupV2Ray — в новом API stateless, явный cleanup не нужен.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayCleanupV2Ray(void);

/**
 * ConvertUrlToConfig — нативный xray-парсер URL → JSON xray-config.

Зачем: убирает огромный куст Dart-парсера (V2RayUrlParser, ~600 строк +
V2RayOutboundGenerator, ~400 строк), который для каждого нового xray-фичи
надо вручную портировать. Здесь xray сам парсит свой URL и возвращает
готовый conf.Config со всеми streamSettings, tlsSettings, realitySettings,
sockopt, fingerprint, alpn, и т.д. — что бы там ни добавил xtls upstream.

Input:  plain URL string ("vless://...?...", "vmess://...", "trojan://...",
        "ss://...", или v2rayN base64-bundle, или Clash YAML)
Output: plain JSON string с полной xray Config (с inbounds/outbounds/etc.)
        либо "FAILED: <reason>" при ошибке парсинга.

На Dart-стороне разбирать вернувшийся JSON и брать только outbounds[0]
(proxy outbound). Inbounds/routing/dns мобила собирает сама.

Под капотом дёргает libxray.ConvertShareLinksToXrayJson (base64-envelope),
здесь делаем удобную plain-string обёртку чтобы Dart-сторона не возилась
с base64.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayConvertUrlToConfig(NSString* _Nullable url);

/**
 * ForceGC — старый custom helper в Libv2ray для memory pressure.
libXray сам делает периодический GC (см. memory_ios.go тик 1сек).
Этот вызов — explicit trigger когда iOS NE получил memory warning.

В новом libxray API нет exported ForceGC, поэтому делаем напрямую
через runtime/debug — это нормально для in-process Go-кода.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayForceGC(void);

/**
 * GetMemoryStats — старый custom helper для diagnostics.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetMemoryStats(void);

/**
 * GetV2RayStatus — старый API возвращал "RUNNING" / "STOPPED".
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetV2RayStatus(void);

/**
 * GetV2RayVersion — возвращает версию xray-core (raw string).
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetV2RayVersion(void);

/**
 * InitializeV2Ray — no-op в новом API (state-less).
Exported as Libv2rayInitializeV2Ray() (gomobile добавляет package prefix).
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayInitializeV2Ray(void);

/**
 * IsV2RayRunning — прямой проброс к новому GetXrayState.
 */
FOUNDATION_EXPORT BOOL Libv2rayIsV2RayRunning(void);

/**
 * ProbeOutbound — honest HTTP-probe через конкретный outbound в работающем
xray-инстансе. Использует session.SetForcedOutboundTagToContext для
принудительной маршрутизации (игнорируя balancer/routing).

Returns JSON-строку с полями:
  outbound_tag, target_url, alive, http_code, rtt_ms, body_excerpt, error, timestamp_ms

Использование Dart (через v2ray_flutter MethodChannel):
  final r = await V2Ray.probeOutbound(
    tag: 'server-15',
    url: 'https://ip.megav.app/',
    timeoutMs: 5000,
  );
  if (r['alive'] && r['http_code'] == 200) {
    // server-15 жив, exit_ip и asn в body_excerpt
  }

Memory: ~1.5 MB на active probe — безопасно для iOS NE jetsam 50MB cap.

Подробности реализации: см. xray/probe_outbound.go.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayProbeOutbound(NSString* _Nullable outboundTag, NSString* _Nullable targetURL, long timeoutMs);

/**
 * StartV2RayWithConfig — упаковывает JSON в base64-request формат
и вызывает новый RunXrayFromJSON. Возвращает "SUCCESS" или "FAILED: ..."
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStartV2RayWithConfig(NSString* _Nullable configJSON);

/**
 * StopV2Ray — обёртка над новым StopXray. Идемпотентный: если xray уже
остановлен, libxray.StopXray() вернёт success=false, err="xray is not
running" — для нас это OK, возвращаем "SUCCESS" (Swift код ждёт что
stop idempotent).
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStopV2Ray(void);

/**
 * TestV2RayConnection — старый API делал ping через test URL.
Возвращаем простой "SUCCESS" — реальный ping делает observatory в xray.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayTestV2RayConnection(NSString* _Nullable url);

#endif
