
// Objective-C API for talking to the following Go packages
//
//	github.com/v2fly/AndroidLibV2rayLite
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libv2ray_FRAMEWORK_H__
#define __Libv2ray_FRAMEWORK_H__

#include "Libv2ray.objc.h"
#include "Universe.objc.h"

#endif
