// Objective-C API for talking to github.com/xtls/libxray/libv2ray Go package.
//   gobind -lang=objc github.com/xtls/libxray/libv2ray
//
// File is generated by gobind. Do not edit.

#ifndef __Libv2ray_H__
#define __Libv2ray_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * CheckVersionX — устаревший alias для XrayVersion.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayCheckVersionX(void);

/**
 * CleanupV2Ray — в новом API stateless, явный cleanup не нужен.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayCleanupV2Ray(void);

/**
 * ConvertUrlToConfig — нативный xray-парсер URL → JSON xray-config.

Зачем: убирает огромный куст Dart-парсера (V2RayUrlParser, ~600 строк +
V2RayOutboundGenerator, ~400 строк), который для каждого нового xray-фичи
надо вручную портировать. Здесь xray сам парсит свой URL и возвращает
готовый conf.Config со всеми streamSettings, tlsSettings, realitySettings,
sockopt, fingerprint, alpn, и т.д. — что бы там ни добавил xtls upstream.

Input:  plain URL string ("vless://...?...", "vmess://...", "trojan://...",
        "ss://...", или v2rayN base64-bundle, или Clash YAML)
Output: plain JSON string с полной xray Config (с inbounds/outbounds/etc.)
        либо "FAILED: <reason>" при ошибке парсинга.

На Dart-стороне разбирать вернувшийся JSON и брать только outbounds[0]
(proxy outbound). Inbounds/routing/dns мобила собирает сама.

Под капотом дёргает libxray.ConvertShareLinksToXrayJson (base64-envelope),
здесь делаем удобную plain-string обёртку чтобы Dart-сторона не возилась
с base64.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayConvertUrlToConfig(NSString* _Nullable url);

/**
 * ForceGC — старый custom helper в Libv2ray для memory pressure.
libXray сам делает периодический GC (см. memory_ios.go тик 1сек).
Этот вызов — explicit trigger когда iOS NE получил memory warning.

В новом libxray API нет exported ForceGC, поэтому делаем напрямую
через runtime/debug — это нормально для in-process Go-кода.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayForceGC(void);

/**
 * GetBuildInfo — JSON с метаданными собранной libv2ray (gomobile wrapper):
xray_version, go_version, libxray_commit (если VCS-stamping есть),
features (карта feature-flags). Главный флаг — pr5805_balancer_dialer.

Dart usage:
  final info = await V2Ray.getBuildInfo();
  if (info['features']['pr5805_balancer_dialer'] != true) {
    // upstream xray без форка — chain-mode не работает,
    // переключаемся на simple-chain через single outbound.
  }

См. libXray/xray/build_info.go — там полное объяснение detection-логики.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetBuildInfo(void);

/**
 * GetMemoryStats — старый custom helper для diagnostics.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetMemoryStats(void);

/**
 * GetObservatoryState — snapshot текущего состояния burstObservatory:
alive/dead/RTT для всех outbound'ов из subjectSelector. Внутренний
доступ к xray-instance, никаких внешних HTTP запросов.

Returns JSON-строку с полями:
  nodes[]:{tag,alive,delay_ms,ping_all,ping_fail,ping_avg,ping_max,
           ping_min,ping_deviation,last_error,last_seen_ms,last_try_ms}
  timestamp_ms
  error (если что-то пошло не так)

Winner balancer'а Dart считает сам: min(delay_ms) среди alive=true.

Использование Dart (через v2ray_flutter MethodChannel):
  final s = await V2Ray.getObservatoryState();
  for (final n in s['nodes']) {
    debugPrint('${n['tag']}: alive=${n['alive']} rtt=${n['delay_ms']}ms');
  }

requestJSON — зарезервирован под будущие расширения (фильтрация по
тегам, например). Сейчас можно передавать "" — игнорируется.

Подробности реализации: см. xray/observatory_state.go.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetObservatoryState(NSString* _Nullable requestJSON);

/**
 * GetV2RayStatus — старый API возвращал "RUNNING" / "STOPPED".
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetV2RayStatus(void);

/**
 * GetV2RayVersion — возвращает версию xray-core (raw string).
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetV2RayVersion(void);

/**
 * InitializeV2Ray — no-op в новом API (state-less).
Exported as Libv2rayInitializeV2Ray() (gomobile добавляет package prefix).
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayInitializeV2Ray(void);

/**
 * IsV2RayRunning — прямой проброс к новому GetXrayState.
 */
FOUNDATION_EXPORT BOOL Libv2rayIsV2RayRunning(void);

/**
 * PprofEnabled — флаг для Swift-стороны чтобы понять, есть ли pprof в
текущем билде Libv2ray.xcframework. Если StartPprof вернёт error
"not_compiled" — pprof отключён, не стоит звать.
 */
FOUNDATION_EXPORT BOOL Libv2rayPprofEnabled(void);

/**
 * ProbeOutbound — honest HTTP-probe через конкретный outbound в работающем
xray-инстансе. Использует session.SetForcedOutboundTagToContext для
принудительной маршрутизации (игнорируя balancer/routing).

Returns JSON-строку с полями:
  outbound_tag, target_url, alive, http_code, rtt_ms, body_excerpt, error, timestamp_ms

Использование Dart (через v2ray_flutter MethodChannel):
  final r = await V2Ray.probeOutbound(
    tag: 'server-15',
    url: 'https://ip.megav.app/',
    timeoutMs: 5000,
  );
  if (r['alive'] && r['http_code'] == 200) {
    // server-15 жив, exit_ip и asn в body_excerpt
  }

Memory: ~1.5 MB на active probe — безопасно для iOS NE jetsam 50MB cap.

Подробности реализации: см. xray/probe_outbound.go.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayProbeOutbound(NSString* _Nullable outboundTag, NSString* _Nullable targetURL, long timeoutMs);

/**
 * StartPprof запускает HTTP-сервер с pprof endpoint'ом на localhost:port.

На iOS Network Extension работает в отдельном процессе, сетевой
listener в нём ограничен sandbox'ом — но localhost loopback РАЗРЕШЁН,
т.к. он не нарушает entitlement'ы. Для доступа с Mac используй iproxy
чтобы пробросить порт через USB (libimobiledevice).

Возвращает JSON со статусом:

	{"ok":true,"port":6060,"url":"http://localhost:6060/debug/pprof/"}
	{"ok":false,"error":"..."}

Двойной вызов безопасен — второй вернёт already_running.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStartPprof(long port);

/**
 * StartV2RayWithConfig — упаковывает JSON в base64-request формат
и вызывает новый RunXrayFromJSON. Возвращает "SUCCESS" или "FAILED: ..."
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStartV2RayWithConfig(NSString* _Nullable configJSON);

/**
 * StopPprof закрывает listener. После этого pprof endpoint становится
недоступен — иначе он живёт до завершения процесса NE.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStopPprof(void);

/**
 * StopV2Ray — обёртка над новым StopXray. Идемпотентный: если xray уже
остановлен, libxray.StopXray() вернёт success=false, err="xray is not
running" — для нас это OK, возвращаем "SUCCESS" (Swift код ждёт что
stop idempotent).
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStopV2Ray(void);

/**
 * TestV2RayConnection — старый API делал ping через test URL.
Возвращаем простой "SUCCESS" — реальный ping делает observatory в xray.
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayTestV2RayConnection(NSString* _Nullable url);

#endif
