// Objective-C API for talking to libv2ray Go package.
//   gobind -lang=objc libv2ray
//
// File is generated by gobind. Do not edit.

#ifndef __Libv2ray_H__
#define __Libv2ray_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Libv2rayCoreController;
@protocol Libv2rayCoreCallbackHandler;
@class Libv2rayCoreCallbackHandler;

@protocol Libv2rayCoreCallbackHandler <NSObject>
- (long)onEmitStatus:(long)p0 p1:(NSString* _Nullable)p1;
- (long)shutdown;
- (long)startup;
@end

/**
 * CoreController manages Xray instances
 */
@interface Libv2rayCoreController : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewCoreController creates a new core controller
 */
- (nullable instancetype)init:(id<Libv2rayCoreCallbackHandler> _Nullable)s;
@property (nonatomic) id<Libv2rayCoreCallbackHandler> _Nullable callbackHandler;
@property (nonatomic) BOOL isRunning;
/**
 * MeasureDelay measures network delay through Xray
 */
- (BOOL)measureDelay:(NSString* _Nullable)url ret0_:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * StartLoop starts Xray with configuration
 */
- (BOOL)startLoop:(NSString* _Nullable)configContent error:(NSError* _Nullable* _Nullable)error;
/**
 * StopLoop stops the Xray instance
 */
- (BOOL)stopLoop:(NSError* _Nullable* _Nullable)error;
@end

/**
 * CheckVersionX returns Xray version
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayCheckVersionX(void);

/**
 * CleanupV2Ray cleans up resources
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayCleanupV2Ray(void);

/**
 * GetV2RayStatus returns current status
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetV2RayStatus(void);

/**
 * GetV2RayVersion returns version information
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayGetV2RayVersion(void);

/**
 * InitializeV2Ray initializes the Xray system for Flutter
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayInitializeV2Ray(void);

/**
 * IsV2RayRunning returns the running status
 */
FOUNDATION_EXPORT BOOL Libv2rayIsV2RayRunning(void);

/**
 * NewCoreController creates a new core controller
 */
FOUNDATION_EXPORT Libv2rayCoreController* _Nullable Libv2rayNewCoreController(id<Libv2rayCoreCallbackHandler> _Nullable s);

/**
 * StartV2RayWithConfig starts Xray with JSON configuration
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStartV2RayWithConfig(NSString* _Nullable configJSON);

/**
 * StopV2Ray stops the Xray instance
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayStopV2Ray(void);

/**
 * TestV2RayConnection tests connection through Xray
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayTestV2RayConnection(NSString* _Nullable url);

@class Libv2rayCoreCallbackHandler;

/**
 * CoreCallbackHandler interface for callbacks
 */
@interface Libv2rayCoreCallbackHandler : NSObject <goSeqRefInterface, Libv2rayCoreCallbackHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (long)onEmitStatus:(long)p0 p1:(NSString* _Nullable)p1;
- (long)shutdown;
- (long)startup;
@end

#endif
